# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stockbazaar.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stockbazaar.proto\"$\n\x0flookupStockName\x12\x11\n\tstockName\x18\x01 \x01(\t\"9\n\x0clookupResult\x12\x12\n\nstockPrice\x18\x01 \x01(\x02\x12\x15\n\rtradingVolume\x18\x02 \x01(\x05\"M\n\x0etradeStockName\x12\x11\n\tstockName\x18\x01 \x01(\t\x12\x15\n\rstockQuantity\x18\x02 \x01(\x05\x12\x11\n\ttradeType\x18\x03 \x01(\t\"\"\n\x0btradeResult\x12\x13\n\x0bresultTrade\x18\x01 \x01(\x05\"8\n\x0fupdateStockName\x12\x11\n\tstockName\x18\x01 \x01(\t\x12\x12\n\nstockPrice\x18\x02 \x01(\x02\"$\n\x0cupdateResult\x12\x14\n\x0cresultUpdate\x18\x01 \x01(\x05\x32\x91\x01\n\x0bStockBazaar\x12+\n\x06Lookup\x12\x10.lookupStockName\x1a\r.lookupResult\"\x00\x12(\n\x05Trade\x12\x0f.tradeStockName\x1a\x0c.tradeResult\"\x00\x12+\n\x06Update\x12\x10.updateStockName\x1a\r.updateResult\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stockbazaar_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOOKUPSTOCKNAME._serialized_start=21
  _LOOKUPSTOCKNAME._serialized_end=57
  _LOOKUPRESULT._serialized_start=59
  _LOOKUPRESULT._serialized_end=116
  _TRADESTOCKNAME._serialized_start=118
  _TRADESTOCKNAME._serialized_end=195
  _TRADERESULT._serialized_start=197
  _TRADERESULT._serialized_end=231
  _UPDATESTOCKNAME._serialized_start=233
  _UPDATESTOCKNAME._serialized_end=289
  _UPDATERESULT._serialized_start=291
  _UPDATERESULT._serialized_end=327
  _STOCKBAZAAR._serialized_start=330
  _STOCKBAZAAR._serialized_end=475
# @@protoc_insertion_point(module_scope)
