# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stockbazaar_pb2 as stockbazaar__pb2


class StockBazaarStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lookup = channel.unary_unary(
                '/StockBazaar/Lookup',
                request_serializer=stockbazaar__pb2.lookupStockName.SerializeToString,
                response_deserializer=stockbazaar__pb2.lookupResult.FromString,
                )
        self.Trade = channel.unary_unary(
                '/StockBazaar/Trade',
                request_serializer=stockbazaar__pb2.tradeStockName.SerializeToString,
                response_deserializer=stockbazaar__pb2.tradeResult.FromString,
                )
        self.Update = channel.unary_unary(
                '/StockBazaar/Update',
                request_serializer=stockbazaar__pb2.updateStockName.SerializeToString,
                response_deserializer=stockbazaar__pb2.updateResult.FromString,
                )


class StockBazaarServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockBazaarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=stockbazaar__pb2.lookupStockName.FromString,
                    response_serializer=stockbazaar__pb2.lookupResult.SerializeToString,
            ),
            'Trade': grpc.unary_unary_rpc_method_handler(
                    servicer.Trade,
                    request_deserializer=stockbazaar__pb2.tradeStockName.FromString,
                    response_serializer=stockbazaar__pb2.tradeResult.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=stockbazaar__pb2.updateStockName.FromString,
                    response_serializer=stockbazaar__pb2.updateResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StockBazaar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StockBazaar(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StockBazaar/Lookup',
            stockbazaar__pb2.lookupStockName.SerializeToString,
            stockbazaar__pb2.lookupResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Trade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StockBazaar/Trade',
            stockbazaar__pb2.tradeStockName.SerializeToString,
            stockbazaar__pb2.tradeResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StockBazaar/Update',
            stockbazaar__pb2.updateStockName.SerializeToString,
            stockbazaar__pb2.updateResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
