# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stockbazaar.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stockbazaar.proto\"$\n\x0flookupStockName\x12\x11\n\tstockName\x18\x01 \x01(\t\"9\n\x0clookupResult\x12\x12\n\nstockPrice\x18\x01 \x01(\x02\x12\x15\n\rstockQuantity\x18\x02 \x01(\x05\"R\n\x0etradeStockName\x12\x11\n\tstockName\x18\x01 \x01(\t\x12\x1a\n\x12stockTradeQuantity\x18\x02 \x01(\x05\x12\x11\n\ttradeType\x18\x03 \x01(\t\"\"\n\x0btradeResult\x12\x13\n\x0bresultTrade\x18\x01 \x01(\x05\"T\n\x10requestStockName\x12\x11\n\tstockName\x18\x01 \x01(\t\x12\x1a\n\x12stockTradeQuantity\x18\x02 \x01(\x05\x12\x11\n\ttradeType\x18\x03 \x01(\t\"\'\n\rrequestResult\x12\x16\n\x0etransactionNum\x18\x01 \x01(\x05\x32`\n\x07\x43\x61talog\x12+\n\x06Lookup\x12\x10.lookupStockName\x1a\r.lookupResult\"\x00\x12(\n\x05Trade\x12\x0f.tradeStockName\x1a\x0c.tradeResult\"\x00\x32\x37\n\x05Order\x12.\n\x07Request\x12\x11.requestStockName\x1a\x0e.requestResult\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stockbazaar_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOOKUPSTOCKNAME._serialized_start=21
  _LOOKUPSTOCKNAME._serialized_end=57
  _LOOKUPRESULT._serialized_start=59
  _LOOKUPRESULT._serialized_end=116
  _TRADESTOCKNAME._serialized_start=118
  _TRADESTOCKNAME._serialized_end=200
  _TRADERESULT._serialized_start=202
  _TRADERESULT._serialized_end=236
  _REQUESTSTOCKNAME._serialized_start=238
  _REQUESTSTOCKNAME._serialized_end=322
  _REQUESTRESULT._serialized_start=324
  _REQUESTRESULT._serialized_end=363
  _CATALOG._serialized_start=365
  _CATALOG._serialized_end=461
  _ORDER._serialized_start=463
  _ORDER._serialized_end=518
# @@protoc_insertion_point(module_scope)
